default_error_replacement_map = {
    "-^l": "¬^l",
    "§": "ę",
    "$": "ę",
    "%": "",
    "&": "",
    "^": "ę",
    "?": "ę",
    "{": "(",
    "0.": "O.",
    "» ": ", ",
    "»": "„",
    "<": "",
    "«": ".",
    "IL": "II.",
    "IH": "III",
    "HI": "III",
    "VH": "VII",
    "XH": "XII",
    "XL": "XI.",
    "XU": "XII",
    "H.": "II.",
    "H,": "II.",
    "UI": "III",
    "IU": "III",
    "8.": "S.",
    "à": "d",
    "Bibi": "Bibl",
    "vergi": "vergl",
    "vergL": "vergl.",
    "vgL": "vgl.",
    "sdi": "sch",
    "Mise.": "Misc.",
    "stör.": "stor.",
    "stör,": "stor.",
    "tarnen": "tamen",
}
